#A makefile consists of targets and commands that need to be executed to reach \
    the target.

all : FORCE

          cipher : cipher.c gcc cipher.c -
    o..\build\Quest_1

#.PHONY : rebuild clean all

        rebuild : clean all

                      clean : rm -
    rf *.o..\..\build

        FORCE: